// <auto-generated/>
#pragma warning disable CS0618
using Maroon.Shop.Api.Client.Api.Order.ByBillingAddressId;
using Maroon.Shop.Api.Client.Api.Order.ByCustomerId;
using Maroon.Shop.Api.Client.Api.Order.ByShippingAddressId;
using Maroon.Shop.Api.Client.Api.Order.Create;
using Maroon.Shop.Api.Client.Api.Order.Item;
using Maroon.Shop.Api.Client.Api.Order.Update;
using Maroon.Shop.Api.Client.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Maroon.Shop.Api.Client.Api.Order
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Order
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public partial class OrderRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ByBillingAddressId property</summary>
        public global::Maroon.Shop.Api.Client.Api.Order.ByBillingAddressId.ByBillingAddressIdRequestBuilder ByBillingAddressId
        {
            get => new global::Maroon.Shop.Api.Client.Api.Order.ByBillingAddressId.ByBillingAddressIdRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ByCustomerId property</summary>
        public global::Maroon.Shop.Api.Client.Api.Order.ByCustomerId.ByCustomerIdRequestBuilder ByCustomerId
        {
            get => new global::Maroon.Shop.Api.Client.Api.Order.ByCustomerId.ByCustomerIdRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ByShippingAddressId property</summary>
        public global::Maroon.Shop.Api.Client.Api.Order.ByShippingAddressId.ByShippingAddressIdRequestBuilder ByShippingAddressId
        {
            get => new global::Maroon.Shop.Api.Client.Api.Order.ByShippingAddressId.ByShippingAddressIdRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Create property</summary>
        public global::Maroon.Shop.Api.Client.Api.Order.Create.CreateRequestBuilder Create
        {
            get => new global::Maroon.Shop.Api.Client.Api.Order.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Update property</summary>
        public global::Maroon.Shop.Api.Client.Api.Order.Update.UpdateRequestBuilder Update
        {
            get => new global::Maroon.Shop.Api.Client.Api.Order.Update.UpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Maroon.Shop.Api.Client.api.Order.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Maroon.Shop.Api.Client.Api.Order.Item.WithOrderItemRequestBuilder"/></returns>
        public global::Maroon.Shop.Api.Client.Api.Order.Item.WithOrderItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("OrderId", position);
                return new global::Maroon.Shop.Api.Client.Api.Order.Item.WithOrderItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Maroon.Shop.Api.Client.Api.Order.OrderRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrderRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Order{?PageNumber*,PageSize*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Maroon.Shop.Api.Client.Api.Order.OrderRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OrderRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Order{?PageNumber*,PageSize*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::Maroon.Shop.Api.Client.Models.OrderResponsePagedResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Maroon.Shop.Api.Client.Models.OrderResponsePagedResponse?> GetAsync(Action<RequestConfiguration<global::Maroon.Shop.Api.Client.Api.Order.OrderRequestBuilder.OrderRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Maroon.Shop.Api.Client.Models.OrderResponsePagedResponse> GetAsync(Action<RequestConfiguration<global::Maroon.Shop.Api.Client.Api.Order.OrderRequestBuilder.OrderRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Maroon.Shop.Api.Client.Models.OrderResponsePagedResponse>(requestInfo, global::Maroon.Shop.Api.Client.Models.OrderResponsePagedResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Maroon.Shop.Api.Client.Api.Order.OrderRequestBuilder.OrderRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Maroon.Shop.Api.Client.Api.Order.OrderRequestBuilder.OrderRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Maroon.Shop.Api.Client.Api.Order.OrderRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Maroon.Shop.Api.Client.Api.Order.OrderRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Maroon.Shop.Api.Client.Api.Order.OrderRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
        #pragma warning disable CS1591
        public partial class OrderRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            public int? PageNumber { get; set; }
            public int? PageSize { get; set; }
        }
    }
}
#pragma warning restore CS0618
