// <auto-generated/>
#pragma warning disable CS0618
using Maroon.Shop.Api.Client.Api.Address;
using Maroon.Shop.Api.Client.Api.Basket;
using Maroon.Shop.Api.Client.Api.BasketItem;
using Maroon.Shop.Api.Client.Api.Customer;
using Maroon.Shop.Api.Client.Api.Order;
using Maroon.Shop.Api.Client.Api.OrderItem;
using Maroon.Shop.Api.Client.Api.Product;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Maroon.Shop.Api.Client.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Address property</summary>
        public global::Maroon.Shop.Api.Client.Api.Address.AddressRequestBuilder Address
        {
            get => new global::Maroon.Shop.Api.Client.Api.Address.AddressRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Basket property</summary>
        public global::Maroon.Shop.Api.Client.Api.Basket.BasketRequestBuilder Basket
        {
            get => new global::Maroon.Shop.Api.Client.Api.Basket.BasketRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The BasketItem property</summary>
        public global::Maroon.Shop.Api.Client.Api.BasketItem.BasketItemRequestBuilder BasketItem
        {
            get => new global::Maroon.Shop.Api.Client.Api.BasketItem.BasketItemRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Customer property</summary>
        public global::Maroon.Shop.Api.Client.Api.Customer.CustomerRequestBuilder Customer
        {
            get => new global::Maroon.Shop.Api.Client.Api.Customer.CustomerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Order property</summary>
        public global::Maroon.Shop.Api.Client.Api.Order.OrderRequestBuilder Order
        {
            get => new global::Maroon.Shop.Api.Client.Api.Order.OrderRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The OrderItem property</summary>
        public global::Maroon.Shop.Api.Client.Api.OrderItem.OrderItemRequestBuilder OrderItem
        {
            get => new global::Maroon.Shop.Api.Client.Api.OrderItem.OrderItemRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Product property</summary>
        public global::Maroon.Shop.Api.Client.Api.Product.ProductRequestBuilder Product
        {
            get => new global::Maroon.Shop.Api.Client.Api.Product.ProductRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Maroon.Shop.Api.Client.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Maroon.Shop.Api.Client.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
