// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Maroon.Shop.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public partial class CreateOrderRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The billingAddressId property</summary>
        public long? BillingAddressId { get; set; }
        /// <summary>The customerId property</summary>
        public long? CustomerId { get; set; }
        /// <summary>The dateCreated property</summary>
        public DateTimeOffset? DateCreated { get; set; }
        /// <summary>The shippingAddressId property</summary>
        public long? ShippingAddressId { get; set; }
        /// <summary>The totalPrice property</summary>
        public decimal? TotalPrice { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Maroon.Shop.Api.Client.Models.CreateOrderRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Maroon.Shop.Api.Client.Models.CreateOrderRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Maroon.Shop.Api.Client.Models.CreateOrderRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "billingAddressId", n => { BillingAddressId = n.GetLongValue(); } },
                { "customerId", n => { CustomerId = n.GetLongValue(); } },
                { "dateCreated", n => { DateCreated = n.GetDateTimeOffsetValue(); } },
                { "shippingAddressId", n => { ShippingAddressId = n.GetLongValue(); } },
                { "totalPrice", n => { TotalPrice = n.GetDecimalValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("billingAddressId", BillingAddressId);
            writer.WriteLongValue("customerId", CustomerId);
            writer.WriteDateTimeOffsetValue("dateCreated", DateCreated);
            writer.WriteLongValue("shippingAddressId", ShippingAddressId);
            writer.WriteDecimalValue("totalPrice", TotalPrice);
        }
    }
}
#pragma warning restore CS0618
