// <auto-generated/>
#pragma warning disable CS0618
using Maroon.Shop.Api.Client.Api.Product.GetById.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Maroon.Shop.Api.Client.Api.Product.GetById
{
    /// <summary>
    /// Builds and executes requests for operations under \api\Product\GetById
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public partial class GetByIdRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Maroon.Shop.Api.Client.api.Product.GetById.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Maroon.Shop.Api.Client.Api.Product.GetById.Item.WithProductItemRequestBuilder"/></returns>
        public global::Maroon.Shop.Api.Client.Api.Product.GetById.Item.WithProductItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("ProductId", position);
                return new global::Maroon.Shop.Api.Client.Api.Product.GetById.Item.WithProductItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Maroon.Shop.Api.Client.Api.Product.GetById.GetByIdRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetByIdRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Product/GetById", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Maroon.Shop.Api.Client.Api.Product.GetById.GetByIdRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetByIdRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/Product/GetById", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
