// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Maroon.Shop.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public partial class CreateOrderItemRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The orderId property</summary>
        public long? OrderId { get; set; }
        /// <summary>The productId property</summary>
        public long? ProductId { get; set; }
        /// <summary>The quantity property</summary>
        public int? Quantity { get; set; }
        /// <summary>The totalPrice property</summary>
        public double? TotalPrice { get; set; }
        /// <summary>The unitPrice property</summary>
        public double? UnitPrice { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Maroon.Shop.Api.Client.Models.CreateOrderItemRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Maroon.Shop.Api.Client.Models.CreateOrderItemRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Maroon.Shop.Api.Client.Models.CreateOrderItemRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "orderId", n => { OrderId = n.GetLongValue(); } },
                { "productId", n => { ProductId = n.GetLongValue(); } },
                { "quantity", n => { Quantity = n.GetIntValue(); } },
                { "totalPrice", n => { TotalPrice = n.GetDoubleValue(); } },
                { "unitPrice", n => { UnitPrice = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("orderId", OrderId);
            writer.WriteLongValue("productId", ProductId);
            writer.WriteIntValue("quantity", Quantity);
            writer.WriteDoubleValue("totalPrice", TotalPrice);
            writer.WriteDoubleValue("unitPrice", UnitPrice);
        }
    }
}
#pragma warning restore CS0618
